### ISSUE TITLE
Simplify use with transparent constructor

### ISSUE THREAD

**Issue by hugobessaa** [caiogondim/logdown#21]
It would be awesome if we could simply `var debug = require('logdown')({prefix: 'foo});` instead of having to call `new` on `Logdown`. I think browser-people used to use jQuery would also prefer `Logdown({prefix: 'foo'});`.

**Comment by caiogondim** [comment]
I thought about it at first, but for me that way of instantiating objects is not explicit enough about what is happening.
And with ES6, `new` is becoming the default way of creating new objects again.

About jQuery, you can use it with or without `new`.
jQuery just protects you in case you forget t use `new`.

BTW, im using the same approach, as you can see [here](https://github.com/caiogondim/logdown/blob/master/src/index.js#L57)
You can use Logdown without the `new` operator, it will behave the same way.

But i don't recommend that pattern.

**Comment by caiogondim** [comment]
And `require('logdown)({prefix: 'foo'})` works, also.

**Comment by hugobessaa** [comment]
Thanks for the explanation :smile:

**Comment by caiogondim** [comment]
Always here to help =)
