### ISSUE TITLE
Color the actual logged text as well

### ISSUE THREAD

**Issue by sylido** [caiogondim/logdown#24]
Is it possible to add color to the logged text as well, of course a slightly different color than the one of the prefix ?

Also, I just noticed that the prefix text isn't getting colored in the correct color, it's stuck on the yellow one, which is the first in the colors array as well...

**Comment by caiogondim** [comment]
About adding color to the logged text, you mean the whole logged text, or just fragments?

And about the prefix getting stuck, can you send me a snippet?
Is it running on the browser or node?

**Comment by sylido** [comment]
Yeah I meant the whole logged text, I kind of did it myself in a semi-weird way and it seems to work - http://pastebin.com/gGhZBYRs - I added a stupid custom separator as well, just makes it clearer for me.

As for the prefix getting stuck, it was the browser version, tried with both the un-minified and minified one and both of them didn't change the color from the log one for me (chrome).

**Comment by caiogondim** [comment]
Will try to reproduce that bug and work on it in a couple hours.

**Comment by caiogondim** [comment]
I still can not reproduce your bug on a Mac.
Tried with Chrome, Safari and Opera.

But i just fixed a regression in the code, it was printing `undefined` at the end of every output.
Could you try it again and let me know if you still can reproduce the bug?

**Comment by sylido** [comment]
Yeah, I was getting the undefined thing too, but I just added a quick check for notText being null or not.

Actually I had to use logdown for the server part as well and I got similar results there as well, I would do log/warn/error and the prefix stayed the same color so I had to tweak it there as well, to get the same result.

I'll try again with your updated version and see what's going on, I'm on win7-64.

**Comment by caiogondim** [comment]
Just tried to reproduce the error here in Node and could not.
Could you please let me if you still have this error with the last version?

**Comment by sylido** [comment]
So I tried both the src and dist versions - they produce the same output for me currently (this is the browser version in chrome) here is a [screenshot](http://imgur.com/mU1kaja). I do have the "don't cache" option enabled in the console, so I don't think it's caching my previous version.

I'm not getting full or different coloring for the 4 different type of logs, but you can see that I am getting the right info,warn,error icons while the log one doesn't have one. Also the "undefined" is still there ?

**Comment by caiogondim** [comment]
The bug should be fixed for now.

About the colors, you only get different colors for each different module.

You can see an example here: http://requirebin.com/?gist=f0edbf0ac509ee0a8350
Don't forget to open DevTools to see it running =)

Let me know if you still have some issues with the lib.
I'm here to make it bug free =)

**Comment by sylido** [comment]
Ah, my bad then - I did see it correct this time, no undefined.

I guess the only thing left is to add the option of colorifying based on the method, and colorifying the whole text. But I guess that's not an issue :) Thanks for the help, will just modify the latest version !

Cheerio.

**Comment by caiogondim** [comment]
I want to keep the library as simple as possible, and Markdown itself does not have support for colors.

**Comment by caiogondim** [comment]
Let me know about some eventual new bugs. Here to help.
