### ISSUE TITLE
Be able to enable/disable logger via environment variable/config file/local storage (Browser) 

### ISSUE THREAD

**Issue by oliverzy** [caiogondim/logdown#30]
It will be great that logdown can be configured via environment variable/config file/local storage (Browser)

**Comment by caiogondim** [comment]
That is a great idea and i will work on it.

For node.js will do through a enviroment variable.
For the browser will use local storage.

**Comment by caiogondim** [comment]
Make it compatible with `util.debuglog` on Node.js 0.12

**Comment by caiogondim** [comment]
Have still to add support to env var `DEBUG` to be compatible with [debug](https://github.com/visionmedia/debug) and localStorage support for the browser.

**Comment by caiogondim** [comment]
Once everything is done i will release a new version and let you know

**Comment by caiogondim** [comment]
Closing this since it is already supported.
