### ISSUE TITLE
Add Bower support

### ISSUE THREAD

**Issue by juanmav** [caiogondim/logdown#31]
It could be great if logdown has bower support.

Thanks
JM

**Comment by caiogondim** [comment]
And it is done.
Can you test it through bower and let me know if everything is ok?

**Comment by juanmav** [comment]
@caiogondim it is working great. Maybe you can make a git tag? So bower can download a fixed version of logdown.

**Comment by mischah** [comment]
:+1: Using Git tags according to version numbers from package.json would be a great addition.
Because otherwise bower is installing always the latest version.

**Comment by david-byng** [comment]
+1. ATM bower records `"logdown": "*"` on `bower install --save logdown` (meaning on install you will always get the latest commit on master, so people working on the project will end up with differing versions).

Bower does not use the version number in the json files, unfortunately.

**Comment by caiogondim** [comment]
Maybe the issue was that i was not pushing the tags. I pushed all the tags now.
Would you mind testing?

**Comment by caiogondim** [comment]
Just uploaded a new version.
Could you test and give me some feedback if everything is ok?

**Comment by david-byng** [comment]
Yes, its working now, thank you :)
